### ISSUE TITLE
Error: "Class "cooldogedev\libBook\LibBook" not found

### ISSUE THREAD

**Issue by gamegam** [nhanaz-pm-pl/RulesBook#1]
[16:55:01.573] [Server thread/CRITICAL]: Error: "Class "cooldogedev\libBook\LibBook" not found" (EXCEPTION) in "plugins/RulesBook-a069690e3d6c8420dbe47e490b8480f2dcba2066/src/NhanAZ/RulesBook/Main" at line 22

**Comment by NhanAZ** [comment]
Please download the plugin here:
https://poggit.pmmp.io/p/RulesBook

**Comment by ClickedTran** [comment]
> [16:55:01.573] [Server thread/CRITICAL]: Error: "Class "cooldogedev\libBook\LibBook" not found" (EXCEPTION) in "plugins/RulesBook-a069690e3d6c8420dbe47e490b8480f2dcba2066/src/NhanAZ/RulesBook/Main" at line 22

Hey,
Maybe you need the file `https://github.com/cooldogepm/libBook/tree/main/src/cooldogedev/libBook` in your server's `Virions` directory (Install as `LibBook` of cooldogepm)

**Comment by NhanAZ** [comment]
Fixed by https://github.com/nhanaz-pm-pl/RulesBook/commit/0f3213f48963ac5bb535d1bb659aa028ef7a0642
